# -*- coding: utf-8 -*-
"""cccf.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HeWJjKlJiu0mU4fSOe1dOgEvF7R6XXb1
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import os

cccf = pd.read_csv('cccf.csv')
cccf

cccf.info()

cc=cccf.loc[:,['cc_username','cc_rating']]
cc

cf=cccf.loc[:,['cf_username','cf_rating']]
cf

new=cccf.dropna(how='any')
new

sns.lmplot(
    data=new,
    x="cc_rating", y="cf_rating",height=8, aspect=1.5 , fit_reg=True,scatter=True
)

slope,intercept=np.polyfit(new['cc_rating'],new['cf_rating'],1) # cf=m*cc+b
slope,intercept

cc['cc_rating'].corr(cf['cf_rating'])

cccf['cf_rating'] = cccf['cf_rating'].fillna(cccf['cc_rating']*slope+intercept)
cccf['cc_rating'] = cccf['cc_rating'].fillna((cccf['cf_rating']-intercept)/slope)

final_csv=cccf
final_csv

final_csv.info()

final_csv.to_csv('final_csv.csv',index=False)